adminLogin:
    path: /admin/login
    controller: App\Controller\AdminController::login

dashboard:
    path: /admin/{cafeteria}/dashboard
    controller: App\Controller\AdminController::dashboard

menuCategory:
    path: /admin/{cafeteria}/menu/category
    controller: App\Controller\MenuController::category
    
menuBundle:
    path: /admin/{cafeteria}/menu/bundle
    controller: App\Controller\MenuController::bundle
    
menuProduct:
    path: /admin/{cafeteria}/menu/product
    controller: App\Controller\MenuController::product
    
POSAccess:
    path: /admin/{cafeteria}/pos/access
    controller: App\Controller\POSController::access

personal:
    path: /admin/{cafeteria}/personal
    controller: App\Controller\AdminController::personal
    
settings:
    path: /admin/{cafeteria}/settings
    controller: App\Controller\AdminController::settings
    
income:
    path: /admin/reports/data
    controller: App\Controller\ReportsController::data
    

    
account:
    path: /admin/account
    controller: App\Controller\AdminController::account
    
activity:
    path: /admin/{cafeteria}/activity
    controller: App\Controller\AdminController::activity
    
balance:
    path: /admin/balance
    controller: App\Controller\AdminController::balance
    
creator:
    path: /admin/appcreator
    controller: App\Controller\AppCreatorController::dragdrop

aboutUs:
    path: /admin/aboutus
    controller: App\Controller\AboutController::aboutUs
    
privacy:
    path: /admin/about/privacynterms
    controller: App\Controller\AboutController::privacyNTerms
    
help:
    path: /admin/about/help
    controller: App\Controller\AboutController::help
    
tutorial:
    path: /admin/about/tutorial
    controller: App\Controller\AboutController::tutorial
 
update:
    path: /admin/{context}/update/{id}
    controller: App\Controller\RDL::update
    
create:
    path: /admin/{cafeteria}/{context}/create
    controller: App\Controller\RDL::create
    
delete:
    path: /admin/{context}/delete/{id}
    controller: App\Controller\RDL::delete    

search:
    path: /admin/search
    controller: App\Controller\SearchController::search
    
resource:
    path: /admin/{cafeteria}/resources/{resource}
    controller: App\Controller\RDL::getResource
    
gqlresource:
    path: /admin/{cafeteria}/gqlresources/{resource}
    controller: App\Controller\RDL::getGQLResource
    
helper:
    path: /admin/{context}  
    controller: App\Controller\Helper::delete
    