adminLogin:
    path: /admin/login
    controller: App\Controller\AdminController::login

dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

menuCategory:
    path: /admin/menu/category
    controller: App\Controller\AdminController::menuCategory
    
menuIngredient:
    path: /admin/menu/ingredient
    controller: App\Controller\AdminController::menuIngredient
    
menuProduct:
    path: /admin/menu/product
    controller: App\Controller\AdminController::menuProduct
    
POSAccess:
    path: /admin/pos/access
    controller: App\Controller\AdminController::POSAccess
  
POSRecord:
    path: /admin/pos/record
    controller: App\Controller\AdminController::POSRecord 

